name: Pre-build rstarter dev container
on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/aswansyahputra/rstarter
        cacheFrom: ghcr.io/aswansyahputra/rstarter
        push: always
